spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fpvhub
    username: fpvhub
    password: fpvhub
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
